import Head from 'next/head'
import Link from 'next/link';
import React, { createContext, useContext } from 'react';
import { useParams, useRouter, useSearchParams, usePathname } from 'next/navigation';

import Image from 'next/image'
import {getSingleService} from '../../lib/getServicesSection.js';
import {getAllTestimonial} from '../../lib/testimonial.js';
import SiteHeader from '../../components/siteheader.js';
import SiteFooter from '../../components/sitefooter.js';
import useScript from '../../hooks/useScript.js';

import { Navigation, Pagination, Scrollbar, A11y,Mousewheel,FreeMode,Autoplay    } from 'swiper/modules';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/mousewheel';
import 'swiper/css/free-mode';



import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

export async function getStaticProps({params } ){
    const serviceID = params.serviceSlug[1];
    const getservicesdata  = await getSingleService(serviceID);
    const testimonial  = await getAllTestimonial();
  return {
    props:{
      servicePageData: getservicesdata,        
      testisection:testimonial
    },

}

} 


export async function getStaticPaths(){   
  
  return{
      paths: [
        "/services/brand-visual-identity/413",
        "/services/content-and-messaging/420",
        "/services/marketing-strategy/415",
        "/services/search-engine-marketing/432",
        "/services/social-media/418",
        "/services/ux-ui-design/416",
        "/services/website-development/417",
      ],
      fallback: false,

}}



export default function ServicePage({servicePageData, testisection}) {
  
  console.log(servicePageData.data.pageBy.serviceInnerFields.serviceFaq);
  const serviceheader     = servicePageData.data.pageBy.serviceInnerFields.header[0];
  const serviceProcesarr  = servicePageData.data.pageBy.serviceInnerFields.serviceProcess
  
  // const searchParams = useSearchParams()
  // console.log(searchParams.get('serviceID'));
  
  const faqlist   = servicePageData.data.pageBy.serviceInnerFields.serviceFaq;

  const alltestimonial = testisection.data.allTestimonial.nodes;
    //useScript('https://code.jquery.com/jquery-3.7.0.min.js');
    //useScript('https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js');
   // useScript('https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js');
    //useScript('./custominit.js');

    // const [expanded, setExpanded] = React.useState(false);

    // const handleChange = (panel) => (event, isExpanded) => {
    //   setExpanded(isExpanded ? panel : false);
    // };
    return(
        <div>
        <Head>
            <title>Nickelbronx</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" async />
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>
       
  
      
  <section className="identity-banner-sec">
    <div className="container2">
      <div className="identity-banner-inner">
        <div className="identity-content-sec">
          <h2 dangerouslySetInnerHTML={{ __html: serviceheader.heading}}></h2>
          <p dangerouslySetInnerHTML={{ __html: serviceheader.descrption}}></p>
        </div>
        <div className="identity-image-sec">
          <img src={serviceheader.image.sourceUrl} />
        </div>
      </div>
    </div>
  </section>
  {/* Visual Identity Banner Section End */}
  {/* Identity Info Section Start */}
  <section className="identity-info-sec">
    <div className="container2">
      
    {
           
    serviceProcesarr.map((ServicePro, index)=>( 
      
      <div className="info-content">
        <div className="icon-part">
          <img src={ServicePro.stepNumberImage.sourceUrl} />
        </div>
        
        <div className="info-list-sec">
          <div className="list-sec">
            <h3>{ServicePro.title}</h3>
            <ul dangerouslySetInnerHTML={{ __html: ServicePro.listTitle}}></ul>
          </div>
          <div className="paragraph-sec">
            <p  dangerouslySetInnerHTML={{ __html: ServicePro.stepDescription}}></p>
          </div>
        </div>
      </div>
      ))}

          <div className="homeportfoliobtn">
							<Link href="/contact" className="home-btn">GET STARTED</Link> 
						</div>
      
      
      
    </div>
  </section>
  {/* Identity Info Section End */}
  {/* Testimonial Section Start */}
  <section className="testimonial-main">
    <div className="container2*">
      <div className="testimonial-inner">
      <Swiper  
      modules={[Navigation, Pagination, Scrollbar, A11y,Mousewheel, Autoplay ]}
      className="testimonial-slider"  
      navigation
      spaceBetween={25}
      slidesPerView={1} 
      onSlideChange={() => console.log('slide change')}
      onSwiper={(swiper) => console.log(swiper)} 
      direction="horizontal"
      autoplay={{
        delay: 8000,        
      }}
      >

        {alltestimonial.map((testiItem, index)=>(    
        <SwiperSlide>
          <div className="testi-box container2">
            <div className="testi-box-inner">
              <div className="testi-img">
                <Image src={testiItem.customfield.clientPhoto.sourceUrl} alt={testiItem.title} height="300" width="300"/>
              </div>
              <div className="testi-content">
                <h2>{testiItem.title} • {testiItem.customfield.company}</h2>
                {/*<h3>they absolutely CRUSHED IT</h3>*/}
                <h3>{testiItem.customfield.testimonialTitle}</h3>
                <div dangerouslySetInnerHTML={{ __html: testiItem.content}}></div>
              </div>
            </div>
          </div>
          </SwiperSlide>
        ))}
            
            </Swiper>   
      </div>
    </div>
  </section>
  {/* Testimonial Section End */}
  {/* FAQ Section Start */}
  <section className="faq-main-sec">
    <div className="container2">
      <div className="faq-title">
        <h2>FAQs</h2>
      </div>

      
      <div className="accordion">
      
      {faqlist.map((faqitem, index)=>(        
      <Accordion key={index}>
          <AccordionSummary id={`panel${index}-header`}  expandIcon={<ExpandMoreIcon />}>
            <h3>{faqitem.quetion}</h3>
          </AccordionSummary>
          <AccordionDetails>
            <p>{faqitem.answer}</p>
          </AccordionDetails>
      </Accordion>
       ))}
    
      </div>
    </div>
  </section>
  


        <SiteFooter className="footercls"/>
      
        </div>
    )
}