import React, { createContext, useContext } from 'react';
import Link from 'next/link';
import Head from 'next/head'

import Image from 'next/image'
import SiteHeader from '../../components/siteheader.js';
import SiteFooter from '../../components/sitefooter.js';
import useScript from '../../hooks/useScript.js';
import {getServicesSections} from '../../lib/getServicesSection.js';
import {getAllTestimonial} from '../../lib/testimonial.js';

import { Navigation, Pagination, Scrollbar, A11y,Mousewheel,FreeMode,Autoplay    } from 'swiper/modules';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/mousewheel';
import 'swiper/css/free-mode';


import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

export async function getStaticProps(){
  const getservicesdata  = await getServicesSections();
  const testimonial  = await getAllTestimonial();
  
  
  return {
      props:{
         servicesData: getservicesdata,  
         testisection:testimonial      
         
      },

  }
}


export default function About({servicesData,testisection}) {
  console.log(servicesData);
  const alltestimonial = testisection.data.allTestimonial.nodes;

    useScript('https://code.jquery.com/jquery-3.7.0.min.js');
    useScript('https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js');
    useScript('https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js');
    useScript('./custominit.js');
    return(
        <>
        <Head>
            <title>Nickelbronx</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"  async/>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" async/>
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>
       
      
  <section className="subservice-banner">
    <div className="container2">
      <div className="subservice-header">
        <h2>Personal Brand</h2>
      </div>
    </div>
  </section>
  <section className="subservice-content">
    <div className="container2">
      <div className="subservice-text">
        <div className="subservice-text-inner">
          <h2>Crafting Your Unique Story</h2>
          <p>
          At NickelBronx, we understand the power of a strong personal brand in today's competitive landscape. 
          Your unique story, values, and aspirations deserve to be highlighted with a distinct and compelling identity. 
          Our seasoned team of marketing and brand design experts is here to amplify your personal brand, creating an authentic and 
          memorable narrative that resonates with your audience. Unlock the full potential of your 
          personal brand with our tailored marketing strategies and brand design expertise. We start by delving into your journey, passions, 
          and the essence of what makes you, well, you! Our collaborative process ensures that every aspect of your personal brand reflects 
          your authenticity and connects deeply with your target audience
          </p>
          <h2>Strategic Marketing and Visual Identity</h2>
          <p>Our marketing strategies are not just about visibility; 
            they are about making a lasting impact. From targeted social media campaigns to personalized content that 
            speaks directly to your audience, we're dedicated to strategically positioning your personal brand for success. 
            Let's turn heads, spark conversations, and build a community around your unique story. A captivating visual identity is the cornerstone of a 
            memorable personal brand. Our talented designers will work closely with you to create a visually stunning and cohesive brand design – 
            from a distinctive logo to eye-catching graphics. Your personal brand deserves to be recognized at a glance, and we're here to make that happen.
          </p>
          <h2>Building Connections, One Click at a Time</h2>
          <p>Your personal brand is not just a logo or a tagline; 
            it's about building genuine connections. Our team excels at creating 
            engaging and authentic content that sparks conversations and fosters meaningful
             connections with your audience. Let's transform your online presence into a thriving hub of 
             engagement and opportunities. Your journey to personal brand excellence begins here. Let us guide you through a 
             transformative experience that will elevate your presence, expand your reach, and establish you as a force to be reckoned with 
             in your industry. Your personal brand is unique – let's make sure the world sees it that way!


          </p>
        </div>
      </div>
      <div className="subservice-boxes">
        <div className="subservice-itembx servcebx1">
          <h4>Brand <br/>
Strategy</h4>
          <p>
          Define your values, mission, and unique selling points to create a strong foundation for your brand.
          </p>
        </div>
        <div className="subservice-itembx servcebx2">
          <h4>Visual <br/>Identity</h4>
          <p>
          Our designers will create a customized logo, color palette, and graphic elements that reflect your personality and resonate with your audience.
          </p>
        </div>
        <div className="subservice-itembx servcebx3">
          <h4>Social Media <br/>Presence</h4>
          <p>
          We'll optimize your profiles, curate engaging content, and implement strategies to grow your followers authentically.
          </p>
        </div>
        <div className="subservice-itembx servcebx2">
          <h4>Content <br/>
Creation</h4>
          <p>
          Our team can provide you with unique and impactful content as well as guide you to personally produce compelling blogs, videos, and social media posts.
          </p>
        </div>
        <div className="subservice-itembx servcebx3">
          <h4>Online <br/>Presence</h4>
          <p>
          We design and develop a personalized website and provide actionable insights on how to enhance your visibility, engagement, in the digital landscape.
          </p>
        </div>
        <div className="subservice-itembx servcebx1">
          <h4>Analytics and <br/>Reporting</h4>
          <p>
          Monitor key metrics like traffic, and customer behavior using analytics tools to gain insights and refine your personal brand strategy.
          </p>
        </div>
      </div>
    </div>
  </section>

  {/* Identity Info Section End */}
  {/* Testimonial Section Start */}
  <section className="testimonial-main">
    <div className="container2*">
      <div className="testimonial-inner">
      <Swiper  
      modules={[Navigation, Pagination, Scrollbar, A11y,Mousewheel, Autoplay ]}
      className="testimonial-slider"  
      navigation
      spaceBetween={25}
      slidesPerView={1} 
      onSlideChange={() => console.log('slide change')}
      onSwiper={(swiper) => console.log(swiper)} 
      direction="horizontal"
      autoplay={{
        delay: 8000,        
      }}
      >

        {alltestimonial.map((testiItem, index)=>(    
        <SwiperSlide>
          <div className="testi-box container2">
            <div className="testi-box-inner">
              <div className="testi-img">
                <Image src={testiItem.customfield.clientPhoto.sourceUrl} alt={testiItem.title} height="300" width="300"/>
              </div>
              <div className="testi-content">
                <h2>{testiItem.title} • {testiItem.customfield.company}</h2>
                {/*<h3>they absolutely CRUSHED IT</h3>*/}
                <h3>{testiItem.customfield.testimonialTitle}</h3>
                <div dangerouslySetInnerHTML={{ __html: testiItem.content}}></div>
              </div>
            </div>
          </div>
          </SwiperSlide>
        ))}
            
            </Swiper>   
      </div>
    </div>
  </section>
  {/* Testimonial Section End */}    


  {/* FAQ Section Start */}
  <section className="faq-main-sec">
    <div className="container2">
      <div className="faq-title">
        <h2>FAQs</h2>
      </div>

      
      <div className="accordion">
      
             
      <Accordion>
          <AccordionSummary id={`panel1-header`}  expandIcon={<ExpandMoreIcon />}>
            <h3>Why is personal branding important in today's professional landscape?</h3>
          </AccordionSummary>
          <AccordionDetails>
            <p>In today's highly competitive and digitalized world, personal branding is crucial for standing out in a crowded marketplace. A strong personal brand helps establish your unique identity, differentiate yourself from others, and build credibility. It not only influences how others perceive you but also opens up opportunities for career advancement, networking, and personal growth.

            </p>
          </AccordionDetails>
      </Accordion>
      <Accordion>
          <AccordionSummary id={`panel1-header`}  expandIcon={<ExpandMoreIcon />}>
            <h3>How can I define my personal brand effectively?</h3>
          </AccordionSummary>
          <AccordionDetails>
            <p>Defining your personal brand begins with a deep self-discovery process. Reflect on your values, strengths, passions, and what makes you unique. Consider the qualities you want to be known for and how you want others to perceive you. Conducting a personal brand audit, seeking feedback from peers, and identifying your target audience are essential steps in creating a clear and authentic personal brand that resonates with your goals.
</p>
          </AccordionDetails>
      </Accordion>
      <Accordion>
          <AccordionSummary id={`panel1-header`}  expandIcon={<ExpandMoreIcon />}>
            <h3>What role does online presence play in personal branding?
</h3>
          </AccordionSummary>
          <AccordionDetails>
            <p>In the digital age, your online presence is a significant component of your personal brand. Social media platforms, personal websites, and professional networking sites offer opportunities to showcase your expertise, share your story, and engage with your audience. Managing your online presence involves curating content that aligns with your personal brand, being mindful of privacy settings, and leveraging digital platforms to amplify your message and connect with your audience effectively.
</p>
          </AccordionDetails>
      </Accordion>
      <Accordion>
          <AccordionSummary id={`panel1-header`}  expandIcon={<ExpandMoreIcon />}>
            <h3>How can personal branding benefit my professional career?

</h3>
          </AccordionSummary>
          <AccordionDetails>
            <p>A well-crafted personal brand can have numerous benefits for your professional career. It can enhance your visibility within your industry, positioning you as an expert or thought leader. A strong personal brand can attract opportunities, such as job offers, partnerships, and speaking engagements. Additionally, it can foster trust and credibility among peers, clients, and employers, contributing to career advancement and long-term success in your chosen field.
</p>
          </AccordionDetails>
      </Accordion>
    
      </div>
    </div>
  </section> 
  
  
  
  
  


        <SiteFooter className="footercls"/>
        </>

    )
}