import Head from 'next/head'
import React, { createContext, useContext } from 'react';
import { useParams, useRouter, useSearchParams, usePathname } from 'next/navigation';
import  { useState, useEffect } from 'react';

import Image from 'next/image'
import {getAllPortfolioSlug, getSinglePortfolio} from '../../lib/getPortfolioSections.js';
import GetPortfolioImagebyType from '../../components/getportfolioByType.js';

import SiteHeader from '../../components/siteheader.js';
import SiteFooter from '../../components/sitefooter.js';


export async function getStaticProps({params} ){
    const portfolioID       = params.portfolioSlug[1];
    const getportfoliodata  = await getSinglePortfolio(portfolioID);
    const allSlugsssss =  await getAllPortfolioSlug();
    
  return {
    props:{
      singleportfolio: getportfoliodata,        
      another:allSlugsssss
    },

}

}

export async function getStaticPaths(){ 
    
   
  
    
    // const allPaths = [];
    // const portslugs = allSlugs.data.allPortfolio.nodes;
    // await allSlugs.data.allPortfolio.nodes.map((ps,index)=>(
    //     allPaths.push (+ps.slug+"/"+ps.portfolioId)
       
    //  ));
    console.log("Helllllla"); 
    return{
        paths: ["/portfolios/joe-mechlinski/571","/portfolios/milkify/660"],
        fallback: true,
  
  }}

  export default function PortfolioPage({singleportfolio, another, paths}) {
    
   

    useEffect( () => { document.querySelector("body").classList.add("transparent-header") } );

        return( 
            <>
                <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                
                <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
                <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" async/>
                <script src="/custominit.js" async></script>
                </Head>
                <SiteHeader className="headercls"/>


                <GetPortfolioImagebyType portfolioItem={singleportfolio} />

                <SiteFooter className="footercls"/>
            </>
        )
         
  }
  
  
  