import Head from 'next/head'
import React, { createContext, useContext } from 'react';
import { useParams, useRouter, useSearchParams, usePathname } from 'next/navigation';
import  { useState, useEffect } from 'react';

import Image from 'next/image'
import {getAllPortfolioSlug, getSinglePortfolio} from '../../lib/getPortfolioSections.js';
import GetPortfolioImagebyType from '../../components/getportfolioByType.js';

import SiteHeader from '../../components/siteheader.js';
import SiteFooter from '../../components/sitefooter.js';
// import useScript from '../../hooks/useScript.js';

export async function getStaticProps({params} ){
    const portfolioID       = params.portfolioSlug[1];
    const getportfoliodata  = await getSinglePortfolio(portfolioID);
    const allSlugsssss =  await getAllPortfolioSlug();
    console.log(params);
    
  return {
    props:{
      singleportfolio: getportfoliodata,        
      another:allSlugsssss
    },

}

}

export async function getStaticPaths(){ 
    
   
     const  allSlugs =  await getAllPortfolioSlug()
    
     const allPaths = [];
     const portslugs = allSlugs.data.allPortfolio.nodes;
    //  allSlugs.data.allPortfolio.nodes.map((ps,index)=>(
    //   allPaths.push ("/portfolios/"+ps.slug+"/"+ps.portfolioId)
       
    //   ));

    // console.log(allSlugs); 
    // return{
    //     paths: portslugs.map((ps)=>({
    //         params:{ portfolioSlug:[`${ps.slug}`, `${ps.portfolioId}`]}
    //       })), 
    //     fallback: false,  
    // }

      let aaaaa = [];
      
      portslugs.map((ps)=>(
         aaaaa.push("/portfolios/"+ps.slug+"/"+ps.portfolioId)
        
      ));
      console.log(aaaaa);
    return{
      paths: aaaaa,
      fallback: false,
    }

}

  export default function PortfolioPage({singleportfolio, another, paths}) {
    
   

    useEffect( () => { document.querySelector("body").classList.add("transparent-header") } );
    // useScript('https://code.jquery.com/jquery-3.7.0.min.js');
    // useScript('https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js');
    // useScript('https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js');
    // useScript('./custominit.js');
        return( 
            <div>
                <Head>
                <title>Nickelbronx</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                
                <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
                <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" async/>
                <script src="/custominit.js" async></script>
                </Head>
                <SiteHeader className="headercls"/>


                <GetPortfolioImagebyType portfolioItem={singleportfolio} />

                <SiteFooter className="footercls"/>
            </div>
        )
         
  }
  
  
  