import React from 'react';
import Link from 'next/link';
import Head from 'next/head'
import Image from 'next/image'
import SiteHeader from '../../components/siteheader.js';
import SiteFooter from '../../components/sitefooter.js';
// import useScript from '../../hooks/useScript.js';
import {getItemsPortfolioPage} from '../../lib/getPortfolioSections.js';



export async function getStaticProps(){
  const getportfoliosdata  = await getItemsPortfolioPage();
  
  
  
  return {
      props:{
         portfoliositems: getportfoliosdata,        
         
      },

  }
}


export default function About({portfoliositems}) {

  const header = portfoliositems.data.pageBy.portfolioPageFields.pageHeading;
  const allitems = portfoliositems.data.pageBy.portfolioPageFields.portfolioItems;
  // console.log(portfoliositems);
  //   useScript('https://code.jquery.com/jquery-3.7.0.min.js');
  //   useScript('https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js');
  //   useScript('https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js');
  //   useScript('./custominit.js');

    return(
        <div>
        <Head>
            <title>Nickelbronx</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            {/* <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async/>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" async/> */}
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>
       
  
  
        <section className="talk-about-main-sec">
  <div className="container2">
    <div className="talk-about-title">
      <h2 className="textcenter" dangerouslySetInnerHTML={{ __html: header}}></h2>
    </div>
    <div className="filter-inner-sec">
      {/* <div className="buttons">
        <button className="button  active" data-attr="all">
          <a href="#">All </a>
        </button>
        <button className="button " data-attr="branding">
          <a href="#">Branding </a>
        </button>
        <button className="button " data-attr="visual-design">
          <a href="#">Visual Design</a>
        </button>
        <button className="button " data-attr="ui-ux">
          <a href="#">UI/UX </a>
        </button>
        <button className="button " data-attr="social-media">
          <a href="#">Social Media </a>
        </button>
      </div> */}
      <div className="portfoliowraper">
      {
           
           allitems.map((portitem, index)=>( 
        <div className='porfoliorow' key={index}>
            <div className="pfrow1">
            <div className="pfitem1 pfitemfilter branding">
                <div className="portfolioimg">
                <a href={"/portfolios/"+portitem.portfolioItemBig.slug+"/"+portitem.portfolioItemBig.portfolioId}
                  className="learn-btn color-yellow" >
                {portitem.portfolioItemBig.portfoliolongfields.portfolioHeaderLong[0] &&(
                    <Image src={portitem.portfolioItemBig.portfoliolongfields.portfolioHeaderLong[0].headerImage.sourceUrl} width={1200} height={500} alt={portitem.portfolioItemBig.slug} /> 
                )}
                {portitem.portfolioItemBig.portfolioshortfields.portfolioHeader[0] &&(
                    <img src={portitem.portfolioItemBig.portfolioshortfields.portfolioHeader[0].headerImage.sourceUrl} alt={portitem.portfolioItemBig.slug}/> 
                )}
                
                </a>
                
                </div>
                <div className="pftitlewraper">
                <h3>{portitem.portfolioItemBig.title}</h3>
                <a>Brand &amp; Website</a>
                </div>
            </div>
            </div>
            <div className="pfrow2">
            <div className="pfitem1 pfitemfilter visual-design">
                <div className="portfolioimg">
                <a href={"/portfolios/"+portitem.portfolioItemSide1.slug+"/"+portitem.portfolioItemSide1.portfolioId}
                  className="learn-btn color-yellow" >
                {portitem.portfolioItemSide1.portfoliolongfields.portfolioHeaderLong[0] &&(
                    <Image src={portitem.portfolioItemSide1.portfoliolongfields.portfolioHeaderLong[0].headerImage.sourceUrl} width={1200} height={500} className="portsideimg" 
                    alt={portitem.portfolioItemSide1.slug} /> 
                    
                )}
                {portitem.portfolioItemSide1.portfolioshortfields.portfolioHeader[0] &&(
                    <Image src={portitem.portfolioItemSide1.portfolioshortfields.portfolioHeader[0].headerImage.sourceUrl}  width={600} height={600} className="portsideimg"
                    alt={portitem.portfolioItemSide1.slug}  /> 
                    
                )}
                </a>
                </div>
                <div className="pftitlewraper">
                <h3>{portitem.portfolioItemSide1.title}</h3>
                <a>Brand &amp; Website</a>
                </div>
            </div>
            <div className="pfitem1 pfitemfilter  ">
                <div className="portfolioimg ">
                <a href={"/portfolios/"+portitem.portfolioItemSide2.slug+"/"+portitem.portfolioItemSide2.portfolioId}
                  className="learn-btn color-yellow" >
                {portitem.portfolioItemSide2.portfoliolongfields.portfolioHeaderLong[0] &&(
                    <Image src={portitem.portfolioItemSide2.portfoliolongfields.portfolioHeaderLong[0].headerImage.sourceUrl} width={1200} height={500} className="portsideimg"
                    alt={portitem.portfolioItemSide2.slug} /> 
                )}
                {portitem.portfolioItemSide2.portfolioshortfields.portfolioHeader[0] &&(
                    <Image src={portitem.portfolioItemSide2.portfolioshortfields.portfolioHeader[0].headerImage.sourceUrl}  width={600} height={600} className="portsideimg" 
                    alt={portitem.portfolioItemSide2.slug} /> 
                )}
              </a>
                </div>
                <div className="pftitlewraper">
                <h3>{portitem.portfolioItemSide2.title}</h3>
                <a>Brand &amp; Website</a>
                </div>
            </div>
            </div>

        </div>
        ))}
        
        
      </div>
    </div>
  </div>
</section>


  
  
  
  
  
  


        <SiteFooter className="footercls"/>
        </div>

    )
}