import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import  { useState, useEffect } from 'react';
import SiteHeader from '../components/siteheader.js';
import SiteFooter from '../components/sitefooter.js';
import useScript from '../hooks/useScript.js';

export async function getStaticProps(){
  
 
  
  
  return {
      props:{
        merchfield: "",
        
      },

  }
  
}


export default function Merch({merchfields}) {
    

  const handleSubmit = async (event) => {
    event.preventDefault();

    const data = {
        cnformname        : event.target.cnformname.value,
        cnformcompany     : event.target.cnformcompany.value,
        cnformemail       : event.target.cnformemail.value,
        cnformphone       : event.target.cnformphone.value,
        lookingfor        : event.target.lookingfor.value,
        cnformbrief        : event.target.cnformbrief.value,
    }

    const jsonData = JSON.stringify(data);

    const response = await fetch('/api/form', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: jsonData,
    });

    const result = await response.json();
    console.log(result.data);


    setSumbitStatus(true);
    setResponseMessage(result.data);

    if(!response.ok) {
        setAlertColor('bg-red-500');
    }
    else {
        setAlertColor('bg-green-500');
    }


}

  useScript('https://code.jquery.com/jquery-3.7.0.min.js');  
  useScript('./custominit.js');
  
  
    return (
        <>
        <Head>
            <title>Nickelbronx</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async/>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" async/>
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>

        <section className="contact-main-sec">
        <div className="container">
        <form className="contact-form" onSubmit={handleSubmit}>
          <div className='contatpgmain'>
              <div className='contactpgleft'>
                    <div className='contactpghead'>
                      <h3>We need<br/><span>copy here</span></h3>
                      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
                    </div>
                    <div className='contactpglinks'>
                        <p><a>hello@nickelbronx.com</a></p>
                        <p><a>(703) 865-2600</a></p>

                    </div>
              </div>
              <div className='contactpgright'>
                  <div className='contactformwhite'>
                      <div className='cnform_wtrow'>
                          <div className='cnformfield_wt'>
                            <label>Name</label>
                            <input type='text' className='cnformwht_text' name='cnformname' id='cnformname' />
                          </div>
                          <div className='cnformfield_wt'>
                            <label>Company Name</label>
                            <input type='text' className='cnformwht_text' name='cnformcompany' id='cnformcompany'  />
                          </div>

                      </div>
                      <div className='cnform_wtrow mt_60'>
                          <div className='cnformfield_wt'>
                            <label>Email</label>
                            <input type='text' className='cnformwht_text' name='cnformemail' id='cnformemail' />
                          </div>
                          <div className='cnformfield_wt'>
                            <label>Phone</label>
                            <input type='text' className='cnformwht_text' name='cnformphone' id='cnformphone'  />
                          </div>
                      </div>
                      <div className='cnform_wtrow mt_60 fullwidth'>
                          <div className='cnformfield_wt'>
                            <label>WHAT ARE YOU LOOKING FOR?</label>
                            <select className='selectfield' name='lookingfor' id='lookingfor'>
                              <option value="New Project Request">New Project Request</option>
                              <option value="Media Inquiry">Media Inquiry</option>
                              <option value="Collabs/Brand Deals">Collabs/Brand Deals</option>
                              <option value="Something Else">Something Else</option>
                            </select>
                          </div>                          
                      </div>
                      <div className='cnform_wtrow mt_60 fullwidth'>
                          <div className='cnformfield_wt'>
                            <label>Project brief</label>
                            <input type='text' className='cnformwht_text' name='cnformbrief' id='cnformbrief' />
                          </div>                          
                      </div>
                      <div className='cnform_wtrow mt_60 fullwidth'>
                          <div className='cnformbtn_wt'>
                              
                              <button className='submitbtn' name='submitform' id='submitform' type="submit">Submit</button>
                          </div>                          
                      </div>
                  </div>
              </div>
          </div>
          </form>
        </div>        
      </section>

  
  


        <SiteFooter className="footercls contactpage"/>
        </>
  )
}

