import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import  { useState, useEffect } from 'react';
import SiteHeader from '../components/siteheader.js';
import SiteFooter from '../components/sitefooter.js';
import useScript from '../hooks/useScript.js';

export async function getStaticProps(){
  
 
  
  
  return {
      props:{
        merchfield: "",
        
      },

  }
  
}


export default function Merch({merchfields}) {
    
  useScript('https://code.jquery.com/jquery-3.7.0.min.js');
  useScript('https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js');
  useScript('https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js');
  useScript('./custominit.js');
  
  
    return (
        <>
        <Head>
            <title>Nickelbronx</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async/>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" async/>
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>

        <section className="contact-main-sec">
        <div className="container">
          <div className="contact-header">
            <h2>LET’S TALK</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit,
              <br /> sed do eiusmod tempor incididunt ut labore et dolore.
            </p>
            <div className="contactformlinks">
              <ul>
                <li>
                  <Link className="contactformbtn" href="/projectrequest">
                    <h3 className='headnewpro'>New Project request</h3>
                  </Link>
                </li>
                <li>
                  <Link className="contactformbtn" href="/media-inquiry">
                  <h3 className='headmedia'>Media Inquiry</h3>
                  </Link>
                </li>
                
                <li>
                  <Link className="contactformbtn" href="/brand-deals">
                  <h3 className='headsomething'>Collabs/Brand Deals</h3>
                  </Link>
                </li>
                <li>
                  <Link className="contactformbtn" href="/something-else">
                  <h3 className=' headcollabs' >Something Else</h3>
                  </Link>
                </li>
                
              </ul>
            </div>
          </div>
        </div>
      </section>

  
  


        {/* <SiteFooter className="footercls"/> */}
        </>
  )
}

