import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import  { useState, useEffect } from 'react';
import SiteHeader from '../components/siteheader.js';
import SiteFooter from '../components/sitefooter.js';


export async function getStaticProps(){
  
 
  
  
  return {
      props:{
        merchfield: "",
        
      },

  }
  
}


export default function Merch({merchfields}) {
    

  
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async/>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" async/>
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>

        <section className="contact-main-sec">
        <div className="container">
          <div className="contact-header">
            <h2>LET’S TALK</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit,
              <br /> sed do eiusmod tempor incididunt ut labore et dolore.
            </p>
            <div className="contactformlinks">
              <ul>
                <li>
                  <Link className="contactformbtn" href="/projectrequest">
                    <img src="/newprojecthead.png" /> 
                  </Link>
                </li>
                <li>
                  <Link className="contactformbtn" href="/about">
                    <img src="/somethingelsehead.png" />
                  </Link>
                </li>
                <li>
                  <Link className="contactformbtn" href="/about">
                    <img src="/collab-brands.png" />
                  </Link>
                </li>
                <li>
                  <Link className="contactformbtn" href="/about">
                    <img src="/media-query.png" />
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

  
  


        <SiteFooter className="footercls"/>
        </>
  )
}

