import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import  { useState, useEffect } from 'react';
import SiteHeader from '../components/siteheader.js';
import SiteFooter from '../components/sitefooter.js';
import useScript from '../hooks/useScript.js';

export async function getStaticProps(){
  
 
  
  
  return {
      props:{
        merchfield: "",
        
      },

  }
  
}


export default function Merch({merchfields}) {
    
  useScript('https://code.jquery.com/jquery-3.7.0.min.js');
  useScript('https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js');
  useScript('https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js');
  useScript('./custominit.js');
  
    return (
        <>
        <Head>
            <title>Nickelbronx</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"  async/>
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>

       
      <section className="identity-banner-sec">
        <div className="container2">
          <div className="identity-banner-inner">
            <div className="productbannertext">
              <h2>
                HOURLY <br />
                <span>POWER</span> PACKS
              </h2>
              <p>
                You’re the best at what you do — but how will anyone know that until
                they actually work with you? Looks aren’t everything.
              </p>
              <a className="home-btn" href="#">
                Get Started
              </a>
            </div>
            <div className="productbannerimage">
              <img src="./productplaceholder.png" height={529} width={529} alt={"hourly nickelbronx package"} />
            </div>
          </div>
        </div>
      </section>
      {/* Visual Identity Banner Section End */}
      <section className="whygetbundle">
        <div className="container2">
          <div className="whybundlehead">
            <h2>
              WHY GET A <span>BUNDLE?</span>
            </h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
              minim veniam, quis nostrud.
            </p>
          </div>
          <div className="bundleboxs">
            <div className="bundlebx">
              <div className="bundleicon">
                <img src="./productbundle3.png" height={103} width={48} alt="Package icon" />
              </div>
              <div className="bundletext ">
                <h3 className="magenta">BENEFIT 1</h3>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod tempor incididunt ut labore et dolore magna aliqua
                </p>
              </div>
            </div>
            <div className="bundlebx">
              <div className="bundleicon">
                <img src="./productbundle2.png" height={103} width={73} alt="Package icon" />
              </div>
              <div className="bundletext ">
                <h3 className="yellow">BENEFIT 1</h3>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod tempor incididunt ut labore et dolore magna aliqua
                </p>
              </div>
            </div>
            <div className="bundlebx">
              <div className="bundleicon">
                <img src="./productbundle.png" height={103} width={108}  alt="Package icon"/>
              </div>
              <div className="bundletext ">
                <h3 className="cyan">BENEFIT 1</h3>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod tempor incididunt ut labore et dolore magna aliqua
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="whygetbundle bgblack">
        <div className="container2">
          <div className="whychoosebundle">
            <div className="whychoosebndhead">
              <h2>WHY CHOOSE A BUNDLE?</h2>
              <h3>
                WE OFFER A RANGE OF SERVICES WITH <span>AN HOURLY BUNDLE</span>
              </h3>
            </div>
            <div className="whychoosebndtext">
              <p>
                our proprietary storytelling process delivers meaningful results for
                partners who are dedicated to improving our world. Our outcomes
                speak for themselves so reach out now to learn more. Our outcomes
                speak for themselves so reach out now.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="getplansec">
        <div className="container2">
          <div className="planhead">
            <h2>
              We’ve got a plan that’s
              <br /> perfect for you.
            </h2>
          </div>
          <div className="getplanboxs">
            <div className="planbox">
              <div className="planbxhead">
                <h3>Basic Plan</h3>
                <h2>
                  20<span>hrs</span>
                </h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod.
                </p>
                <hr className="plansep" />
              </div>
              <div className="planbxfeatures">
                <h3>FEATURES</h3>
                <ul className="planfeatlist">
                  <li>Lorem ipsum dolor sit amet</li>
                  <li>Consectetur adipiscing elit</li>
                  <li>tempor incididunt ut</li>
                  <li>Exercitation ullamco laboris</li>
                  <li>Occaecat cupidatat nonplan</li>
                </ul>
              </div>
            </div>
            <div className="planbox">
              <div className="planbxhead">
                <h3>Basic Plan</h3>
                <h2>
                  40<span>hrs</span>
                </h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod.
                </p>
                <hr className="plansep" />
              </div>
              <div className="planbxfeatures">
                <h3>FEATURES</h3>
                <ul className="planfeatlist">
                  <li>Lorem ipsum dolor sit amet</li>
                  <li>Consectetur adipiscing elit</li>
                  <li>tempor incididunt ut</li>
                  <li>Exercitation ullamco laboris</li>
                  <li>Occaecat cupidatat nonplan</li>
                </ul>
              </div>
            </div>
            <div className="planbox">
              <div className="planbxhead">
                <h3>Basic Plan</h3>
                <h2>
                  80<span>hrs</span>
                </h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod.
                </p>
                <hr className="plansep" />
              </div>
              <div className="planbxfeatures">
                <h3>FEATURES</h3>
                <ul className="planfeatlist">
                  <li>Lorem ipsum dolor sit amet</li>
                  <li>Consectetur adipiscing elit</li>
                  <li>tempor incididunt ut</li>
                  <li>Exercitation ullamco laboris</li>
                  <li>Occaecat cupidatat nonplan</li>
                </ul>
              </div>
            </div>
          </div>
          <div className="planstartbtn">
            <a className="home-btn" href="#">
              Get Started
            </a>
          </div>
        </div>
      </section>



  
  


        <SiteFooter className="footercls"/>
        </>
  )
}

