import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import  { useState, useEffect } from 'react';
import {getproductdata} from '../lib/getProductPlan.js';
import SiteHeader from '../components/siteheader.js';
import SiteFooter from '../components/sitefooter.js';
import useScript from '../hooks/useScript.js';

export async function getStaticProps(){
  
  const getproductfields = await getproductdata();
  
  
  return {
      props:{
        productfields: getproductfields,
        
      },

  }
  
}


export default function Merch({productfields}) {
  console.log(productfields.data.pageBy.productLandingPageFields);

  const pageheader        = productfields.data.pageBy.productLandingPageFields.header[0];
  const whygetbundle      = productfields.data.pageBy.productLandingPageFields.whyGetBundle[0];
  const bundleboxes       = productfields.data.pageBy.productLandingPageFields.bundleBoxes;
  const whychoosebundle   = productfields.data.pageBy.productLandingPageFields.whyChooseBundle[0];
  const planHeading       = productfields.data.pageBy.productLandingPageFields.planHeading;
  const plansboxes       = productfields.data.pageBy.productLandingPageFields.plansSection;
    
  useScript('https://code.jquery.com/jquery-3.7.0.min.js');
  useScript('https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js');
  useScript('https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js');
  useScript('./custominit.js');
  
    return (
        <div>
        <Head>
            <title>Nickelbronx</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"  async/>
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>

       
      <section className="identity-banner-sec">
        <div className="container2">
          <div className="identity-banner-inner">
            <div className="productbannertext">
              <h2 dangerouslySetInnerHTML={{ __html: pageheader.heading}}></h2>
              <p>
              {pageheader.description}
              </p>
              <a className="home-btn" href="#">
                Get Started
              </a>
            </div>
            <div className="productbannerimage">
              <img src={pageheader.headerImage.sourceUrl} height={529} width={529} alt={"hourly nickelbronx package"} />
             
            </div>
          </div>
        </div>
      </section>
      {/* Visual Identity Banner Section End */}
      <section className="whygetbundle">
        <div className="container2">
          <div className="whybundlehead">
            <h2 dangerouslySetInnerHTML={{ __html: whygetbundle.heading}}></h2>
            <p>{whygetbundle.description}</p>
          </div>
          <div className="bundleboxs">
            
            {
              bundleboxes.map((bundleitem, index)=>( 


             
            <div className="bundlebx">
              <div className="bundleicon">
                <img src={bundleitem.boxIcon.sourceUrl} height={103} width={48} alt="Package icon" />
              </div>
              <div className="bundletext ">
                <h3>{bundleitem.heading}</h3>
                <p>{bundleitem.description}</p>
              </div>
            </div>
             ))

            }
          </div>
        </div>
      </section>
      <section className="whygetbundle bgblack">
        <div className="container2">
          <div className="whychoosebundle">
            <div className="whychoosebndhead">
              <h2>{whychoosebundle.subHeading}</h2>
              <h3 dangerouslySetInnerHTML={{ __html: whychoosebundle.heading}}></h3>
            </div>
            <div className="whychoosebndtext">
              <p>{whychoosebundle.description}</p>
            </div>
          </div>
        </div>
      </section>
      <section className="getplansec">
        <div className="container2">
          <div className="planhead">
            <h2 dangerouslySetInnerHTML={{ __html: planHeading}}></h2>
          </div>
          <div className="getplanboxs">
            
          {
              plansboxes.map((planitem, index)=>(
            <div className="planbox">
              <div className="planbxhead">
                <h3>{planitem.planName}</h3>
                <h2>
                {planitem.planPrice}<span>hrs</span>
                </h2>
                <p>{planitem.description}</p>
                <hr className="plansep" />
              </div>
              <div className="planbxfeatures">
                <h3>FEATURES</h3>
                
                <ul dangerouslySetInnerHTML={{ __html: planitem.features}}></ul>
              </div>
            </div>
            ))

          }
            
          </div>
          <div className="planstartbtn">
            <a className="home-btn" href="#">
              Get Started
            </a>
          </div>
        </div>
      </section>



  
  


        <SiteFooter className="footercls"/>
        </div>
  )
}

