import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import  { useState, useEffect } from 'react';
import SiteHeader from '../components/siteheader.js';
import SiteFooter from '../components/sitefooter.js';


export async function getStaticProps(){
  
 
  
  
  return {
      props:{
        merchfield: "",
        
      },

  }
  
}


export default function Merch({merchfields}) {
    

  
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"  async/>
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>

        <section className="contact-main-sec">
          <div className="container">

            <div className='prstep1 formsteps'>
                  <div className='formstepinner'>
                    <p>01/06 </p>
                    <h3>What’s your name?</h3>

                  </div>
                  <div className='formfield'>
                      <input type='text' name="prname" id='prname'></input>
                  </div>

            </div>
          
            <div className='prstep1'>
                  <div className='formstepinner'>
                    <p>01/06 </p>
                    <h3>What’s the name of your company?</h3>
                  </div>
                  <div className='formfield'>
                      <input type='text' name="prname" id='prname'></input>
                  </div>

            </div>

            <div className='prstep1'>
                  <div className='formstepinner'>
                    <p>01/06 </p>
                    <h3>Let us know where you’re at in your business and how we can help.</h3>
                  </div>
                  <div className='formfield'>
                      <input type='text' name="prname" id='prname'></input>
                  </div>

            </div>

            <div className='prstep1'>
                  <div className='formstepinner'>
                    <p>01/06 </p>
                    <h3>Tell us more about your project and needs.</h3>
                  </div>
                  <div className='formfield'>
                      <input type='text' name="prname" id='prname'></input>
                  </div>

            </div>

            <div className='prstep1'>
                  <div className='formstepinner'>
                    <p>01/06 </p>
                    <h3>What’s an email we can reach you at?</h3>
                  </div>
                  <div className='formfield'>
                      <input type='text' name="prname" id='prname'></input>
                  </div>

            </div>

            <div className='prstep1'>
                  <div className='formstepinner'>
                    <p>01/06 </p>
                    <h3>Would you like to recieve occasional email updates from NickelBronx?</h3>
                  </div>
                  <div className='formfield'>
                      <input type='text' name="prname" id='prname'></input>
                  </div>

            </div>

            <div className='prstep1'>
                <div className='formstepinner'>
                    <p>01/06 </p>
                    <h3>What’s your name?</h3>
                  </div>
                  <div className='formfield'>
                      <input type='text' name="prname" id='prname'></input>
                  </div>

            </div>
          </div>
        </section>

  
  


        <SiteFooter className="footercls"/>
        </>
  )
}

