'use client';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import  { useState, useEffect, useRef } from 'react';
import SiteHeader from '../components/siteheader.js';
import SiteFooter from '../components/sitefooter.js';
import useScript from '../hooks/useScript.js';

import Lenis from '@studio-freight/lenis'
import { useTransform, useScroll, motion } from 'framer-motion';

export async function getStaticProps(){
  
 
  
  
  return {
      props:{
        merchfield: "",
        
      },

  }
  
}
const images = [

  "1.jpg",

  "2.jpg",

  "3.jpg",

  "4.jpg",

  "5.jpg",

  "6.jpg",

  "7.jpg",

  "8.jpg",

  "9.jpg",

  "10.jpg",

  "11.jpg",

  "12.jpg",

]

export default function Merch({merchfields}) {
    
  useScript('https://code.jquery.com/jquery-3.7.0.min.js');
  useScript('https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js');
  useScript('https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js');
  useScript('./custominit.js');
  
  const [step, SetStep] = useState(1);
  useEffect( () => {

    const lenis = new Lenis()


    const raf = (time) => {

      lenis.raf(time)

      requestAnimationFrame(raf)

    }


    requestAnimationFrame(raf)

  }, [])

    return (
        <>
        <Head>
            <title>Nickelbronx</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"  async/>
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>

        

  
        <main className={styles.main}>

<div className={styles.spacer}></div>

<div className={styles.gallery}>

  <div className={styles.galleryWrapper}>

    <Column images={[images[0], images[1], images[2]]}/>

    <Column images={[images[3], images[4], images[5]]}/>

    <Column images={[images[6], images[7], images[8]]}/>

    <Column images={[images[9], images[10], images[11]]}/>

  </div>

</div>

<div className={styles.spacer}></div>

</main>


        {/* <SiteFooter className="footercls"/> */}
        </>
  )
}

const Column = ({images}) => {

  return (

    <div 

      className={styles.column}

      >

      {

        images.map( (src, i) => {

          return <div key={i} className={styles.imageContainer}>

            <Image 

              src={`/images/${src}`}

              alt='image'

              fill

            />

          </div>

        })

      }

    </div>

  )

}