import Head from 'next/head'
import Link from 'next/link';

import React, { createContext, useContext } from 'react';
import { useParams, useRouter, useSearchParams, usePathname } from 'next/navigation';
import Image from 'next/image'
import {getSinglePost,getallPost} from '../../lib/getBlogsSection.js';
import SiteHeader from '../../components/siteheader.js';
import SiteFooter from '../../components/sitefooter.js';
import useScript from '../../hooks/useScript.js';
import {getAllPortfolioSlug} from '../../lib/getPortfolioSections.js';





export async function getStaticProps({params } ){
    const postID = params.postSlug[1];
    const getsinglePost  = await getSinglePost(postID);
    // const getrelatedpost = await getSinglePost(980);
    
  return {
    props:{
      singlepostdata: getsinglePost,        
      
    },

}

} 


export async function getStaticPaths(){   
    const testetete  = await getallPost();
    const allpostitems = testetete.data.posts.nodes;
    console.log(allpostitems);
    let allpostslugs = [];
    allpostitems.map((postslug, index)=>( 
        allpostslugs.push("/blogs/"+postslug.slug+"/"+postslug.postId)
    ))
    console.log(allpostslugs);
  return{
      paths: allpostslugs,
      fallback: false,

}}



export default function ServicePage({singlepostdata}) {
  
  

  const postcontent = singlepostdata.data.postBy;
  const categorylist = singlepostdata.data.postBy.categories.nodes;
  
  const relatedpost = singlepostdata.data.postBy.selectRelatedPostHere.relatedPost;
  console.log(relatedpost.relatedPost);
  // const searchParams = useSearchParams()
  // console.log(searchParams.get('serviceID'));
  
  useScript('https://code.jquery.com/jquery-3.7.0.min.js');
    useScript('https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js');
    useScript('https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js');
    useScript('./custominit.js');
    return(
        <div>
        <Head>
            <title>Nickelbronx</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            
            <script src="https://code.jquery.com/jquery-3.7.0.min.js" async></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" async />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" async />
            <script src="/custominit.js" async></script>
        </Head>
        <SiteHeader className="headercls"/>
       
  
      
  
        <section className="singlepostmain">
  <div className="container2">
    <div className="singlepost-title">
      <h2>{postcontent.title}</h2>
    </div>
    <div className="singlepost-date">
      <a className="postauthor">Alejandra Bernard</a> <a>February 23, 2022 {postcontent.date} </a>
    </div>
    <div className="singlepost-image">
      
      <Image src={postcontent.featuredImage.node.sourceUrl} width={1400} height={300} className="blogimage" alt={postcontent.title}/>
    </div>
    <div className="singlepost-category">
        {
           
           categorylist.map((category, index)=>(   
           <Link href="#">{category.name}</Link>  
           ))
        
           }
        
    </div>
    <div className="singlepost-content" dangerouslySetInnerHTML={{ __html: postcontent.content}}>
      
    </div>
    <div className="singlepost-related">
      <div className="relatedheading">
        <h3>
          RELATED
          <br /> POST
        </h3>
        <h4><Link href={"/blogs/"+relatedpost.slug+"/"+relatedpost.postId}>{relatedpost.title}</Link></h4>
        <div dangerouslySetInnerHTML={{ __html: relatedpost.content.substring(0, 300)}}></div>
      </div>
      <div className="relatedimg">
        <Link href={"/blogs/"+relatedpost.slug+"/"+relatedpost.postId}>
          <Image src={relatedpost.featuredImage.node.sourceUrl} width={600} height={300} className="blogimage" alt={relatedpost.slug}/>
        </Link>
      </div>
    </div>
  </div>
</section>



        <SiteFooter className="footercls"/>
      
        </div>
    )
}